import plate1 from '../images/SmallPlate/plate1.png'
import plate2 from '../images/SmallPlate/plate2.png'
import plate3 from '../images/SmallPlate/plate3.png'
import plate4 from '../images/SmallPlate/plate4.png'
import plate5 from '../images/SmallPlate/plate5.png'
import plate6 from '../images/SmallPlate/plate6.png'
import plate7 from '../images/SmallPlate/plate7.png'
import plate8 from '../images/SmallPlate/plate8.png'
import plate9 from '../images/SmallPlate/plate9.png'

plate1.name = 'Spring Rolls'
plate2.name = 'Chicken Wings'
plate3.name = 'Crab Wontons'
plate4.name = 'Fried Tofu'
plate5.name = 'Grilled Beef'
plate6.name = 'Northeastern Thai Fermented Sausage'
plate7.name = 'Fresh roll'
plate8.name = 'Tod Mun Pla'
plate9.name = 'Spare Ribs'

export default [plate1, plate2, plate3, plate4, plate5, plate6, plate7, plate8, plate9]